export default [
    {
        "html": true,
        "name": "Footer_11",
        "data": "<footer class=\"fdb-block footer-small\">\n      <div class=\"container\">\n        <div class=\"row text-center\">\n          <div class=\"col\">\n            <p>© 2018 Froala. All Rights Reserved</p>\n          </div>\n        </div>\n      </div>\n    </footer>"
    },
    {
        "html": true,
        "name": "Footer_21",
        "data": "<footer class=\"fdb-block footer-small bg-dark\">\n      <div class=\"container\">\n        <div class=\"row align-items-center\">\n          <div class=\"col-12 col-md-8\">\n            <ul class=\"nav justify-content-center justify-content-md-start\">\n              <li class=\"nav-item\">\n                <a class=\"nav-link active\" href=\"https://www.froala.com\">Home</a>\n              </li>\n              <li class=\"nav-item\">\n                <a class=\"nav-link\" href=\"https://www.froala.com\">Features</a>\n              </li>\n              <li class=\"nav-item\">\n                <a class=\"nav-link\" href=\"https://www.froala.com\">Terms</a>\n              </li>\n              <li class=\"nav-item\">\n                <a class=\"nav-link\" href=\"https://www.froala.com\">About</a>\n              </li>\n            </ul>\n          </div>\n    \n          <div class=\"col-12 col-md-4 mt-4 mt-md-0 text-center text-md-right\">\n            © 2018 Froala. All Rights Reserved\n          </div>\n        </div>\n      </div>\n    </footer>"
    },
    {
        "html": true,
        "name": "Footer_31",
        "data": "<footer class=\"fdb-block footer-small\">\n      <div class=\"container\">\n        <div class=\"row text-center align-items-center\">\n          <div class=\"col-12 col-md-8\">\n            <ul class=\"nav justify-content-center justify-content-md-start align-items-center\">\n              <li class=\"nav-item\">\n                <a class=\"nav-link active\" href=\"https://www.froala.com\">\n                    <img alt=\"image\" src=\"https://heroic-empanada-f5b342.netlify.app/logo.png\" height=\"40\">\n                  </a>\n              </li>\n              <li class=\"w-100 d-block d-sm-none\"></li>\n              <li class=\"nav-item\">\n                <a class=\"nav-link\" href=\"https://www.froala.com\">Features</a>\n              </li>\n              <li class=\"nav-item\">\n                <a class=\"nav-link\" href=\"https://www.froala.com\">Terms</a>\n              </li>\n              <li class=\"nav-item\">\n                <a class=\"nav-link\" href=\"https://www.froala.com\">About</a>\n              </li>\n            </ul>\n          </div>\n    \n          <div class=\"col-12 col-md-4 mt-4 mt-md-0 text-md-right\">\n            © 2013-2018 Froala\n          </div>\n        </div>\n      </div>\n    </footer>"
    },
    {
        "html": true,
        "name": "Footer_41",
        "data": "<footer class=\"fdb-block footer-small\">\n      <div class=\"container\">\n        <div class=\"row text-center align-items-center\">\n          <div class=\"col-12 col-sm-6 col-md-4 text-sm-left\">\n            <img alt=\"image\" src=\"https://heroic-empanada-f5b342.netlify.app/logo.png\" height=\"40\">\n          </div>\n    \n          <div class=\"col-12 col-sm-6 col-md-4 mt-4 mt-sm-0 text-center text-sm-right text-md-center\">\n            © 2013-2018 Froala\n          </div>\n    \n          <div class=\"col-12 col-md-4 mt-4 mt-md-0 text-center text-md-right\">\n            <a href=\"https://www.froala.com\" class=\"mx-2\"><i class=\"fab fa-twitter\" aria-hidden=\"true\"></i></a>\n            <a href=\"https://www.froala.com\" class=\"mx-2\"><i class=\"fab fa-facebook\" aria-hidden=\"true\"></i></a>\n            <a href=\"https://www.froala.com\" class=\"mx-2\"><i class=\"fab fa-instagram\" aria-hidden=\"true\"></i></a>\n            <a href=\"https://www.froala.com\" class=\"mx-2\"><i class=\"fab fa-pinterest\" aria-hidden=\"true\"></i></a>\n            <a href=\"https://www.froala.com\" class=\"mx-2\"><i class=\"fab fa-google\" aria-hidden=\"true\"></i></a>\n          </div>\n        </div>\n      </div>\n    </footer>"
    },
    {
        "html": true,
        "name": "Footer_51",
        "data": "<footer class=\"fdb-block footer-small\">\n      <div class=\"container\">\n        <div class=\"row align-items-center\">\n          <div class=\"col-12 col-md-6\">\n            <ul class=\"nav justify-content-center justify-content-md-start\">\n              <li class=\"nav-item\">\n                <a class=\"nav-link active\" href=\"https://www.froala.com\">Home</a>\n              </li>\n              <li class=\"nav-item\">\n                <a class=\"nav-link\" href=\"https://www.froala.com\">Features</a>\n              </li>\n              <li class=\"nav-item\">\n                <a class=\"nav-link\" href=\"https://www.froala.com\">Terms</a>\n              </li>\n              <li class=\"nav-item\">\n                <a class=\"nav-link\" href=\"https://www.froala.com\">About</a>\n              </li>\n            </ul>\n          </div>\n    \n          <div class=\"col-12 col-md-6 mt-4 mt-md-0 text-center text-md-right\">\n            <a href=\"https://www.froala.com\" class=\"mx-2\"><i class=\"fab fa-twitter\" aria-hidden=\"true\"></i></a>\n            <a href=\"https://www.froala.com\" class=\"mx-2\"><i class=\"fab fa-facebook\" aria-hidden=\"true\"></i></a>\n            <a href=\"https://www.froala.com\" class=\"mx-2\"><i class=\"fab fa-instagram\" aria-hidden=\"true\"></i></a>\n            <a href=\"https://www.froala.com\" class=\"mx-2\"><i class=\"fab fa-pinterest\" aria-hidden=\"true\"></i></a>\n            <a href=\"https://www.froala.com\" class=\"mx-2\"><i class=\"fab fa-google\" aria-hidden=\"true\"></i></a>\n          </div>\n        </div>\n      </div>\n    </footer>"
    },
    {
        "html": true,
        "name": "Footer_61",
        "data": "<footer class=\"fdb-block footer-small bg-dark\">\n      <div class=\"container\">\n        <div class=\"row text-center align-items-center\">\n          <div class=\"col\">\n            <ul class=\"nav justify-content-center\">\n              <li class=\"nav-item\">\n                <a class=\"nav-link active\" href=\"https://www.froala.com\">Home</a>\n              </li>\n              <li class=\"nav-item\">\n                <a class=\"nav-link\" href=\"https://www.froala.com\">Features</a>\n              </li>\n              <li class=\"nav-item\">\n                <a class=\"nav-link\" href=\"https://www.froala.com\">Privacy Policy</a>\n              </li>\n              <li class=\"nav-item\">\n                <a class=\"nav-link\" href=\"https://www.froala.com\">Terms</a>\n              </li>\n              <li class=\"nav-item\">\n                <a class=\"nav-link\" href=\"https://www.froala.com\">About</a>\n              </li>\n            </ul>\n    \n            <p class=\"h5 mt-5\">© 2013-2018 Froala</p>\n          </div>\n        </div>\n      </div>\n    </footer>"
    },
    {
        "html": true,
        "name": "Footer_71",
        "data": "<footer class=\"fdb-block footer-small\">\n      <div class=\"container\">\n        <div class=\"row text-center align-items-center\">\n          <div class=\"col-12 col-lg-2 text-lg-left\">\n            <img alt=\"image\" src=\"https://heroic-empanada-f5b342.netlify.app/logo.png\" height=\"40\">\n          </div>\n    \n          <div class=\"col mt-4 mt-lg-0 text-center\">\n            <ul class=\"nav justify-content-center\">\n              <li class=\"nav-item\">\n                <a class=\"nav-link active\" href=\"https://www.froala.com\">Home</a>\n              </li>\n              <li class=\"nav-item\">\n                <a class=\"nav-link\" href=\"https://www.froala.com\">Features</a>\n              </li>\n              <li class=\"nav-item\">\n                <a class=\"nav-link\" href=\"https://www.froala.com\">Privacy Policy</a>\n              </li>\n              <li class=\"nav-item\">\n                <a class=\"nav-link\" href=\"https://www.froala.com\">Terms</a>\n              </li>\n              <li class=\"nav-item\">\n                <a class=\"nav-link\" href=\"https://www.froala.com\">About</a>\n              </li>\n            </ul>\n          </div>\n    \n          <div class=\"col-12 col-lg-2 mt-4 mt-lg-0 text-lg-right\">\n            <a href=\"https://www.froala.com\" class=\"mx-2\"><i class=\"fab fa-twitter\" aria-hidden=\"true\"></i></a>\n            <a href=\"https://www.froala.com\" class=\"mx-2\"><i class=\"fab fa-facebook\" aria-hidden=\"true\"></i></a>\n            <a href=\"https://www.froala.com\" class=\"mx-2\"><i class=\"fab fa-instagram\" aria-hidden=\"true\"></i></a>\n            <a href=\"https://www.froala.com\" class=\"mx-2\"><i class=\"fab fa-pinterest\" aria-hidden=\"true\"></i></a>\n            <a href=\"https://www.froala.com\" class=\"mx-2\"><i class=\"fab fa-google\" aria-hidden=\"true\"></i></a>\n          </div>\n        </div>\n    \n        <div class=\"row mt-4\">\n          <div class=\"col text-center\">\n            © 2018 Froala. All Rights Reserved\n          </div>\n        </div>\n      </div>\n    </footer>"
    },
    {
        "html": true,
        "name": "Footer_81",
        "data": "<footer class=\"fdb-block footer-small\">\n      <div class=\"container\">\n        <div class=\"row align-items-center\">\n          <div class=\"col-12 col-md-6\">\n            <ul class=\"nav justify-content-center justify-content-md-start\">\n              <li class=\"nav-item\">\n                <a class=\"nav-link active\" href=\"https://www.froala.com\">Home</a>\n              </li>\n              <li class=\"nav-item\">\n                <a class=\"nav-link\" href=\"https://www.froala.com\">Features</a>\n              </li>\n              <li class=\"nav-item\">\n                <a class=\"nav-link\" href=\"https://www.froala.com\">Terms</a>\n              </li>\n              <li class=\"nav-item\">\n                <a class=\"nav-link\" href=\"https://www.froala.com\">About</a>\n              </li>\n            </ul>\n          </div>\n    \n          <div class=\"col mt-4 mt-md-0 text-center text-md-right\">\n            <a href=\"https://www.froala.com\" class=\"btn btn-primary\">Contact Us</a>\n          </div>\n        </div>\n      </div>\n    </footer>"
    },
    {
        "html": true,
        "name": "Footer_91",
        "data": "<footer class=\"fdb-block footer-large\">\n      <div class=\"container\">\n        <div class=\"row align-items-top text-center\">\n          <div class=\"col-12 col-sm-6 col-md-4 col-lg-3 text-sm-left\">\n            <h3><strong>Group 1</strong></h3>\n            <nav class=\"nav flex-column\">\n              <a class=\"nav-link active\" href=\"https://www.froala.com\">Home</a>\n              <a class=\"nav-link\" href=\"https://www.froala.com\">Features</a>\n              <a class=\"nav-link\" href=\"https://www.froala.com\">Pricing</a>\n              <a class=\"nav-link\" href=\"https://www.froala.com\">Team</a>\n              <a class=\"nav-link\" href=\"https://www.froala.com\">Contact Us</a>\n            </nav>\n          </div>\n    \n          <div class=\"col-12 col-sm-6 col-md-4 col-lg-3 mt-5 mt-sm-0 text-sm-left\">\n            <h3><strong>Group 2</strong></h3>\n            <nav class=\"nav flex-column\">\n              <a class=\"nav-link active\" href=\"https://www.froala.com\">Privacy Policy</a>\n              <a class=\"nav-link\" href=\"https://www.froala.com\">Terms</a>\n              <a class=\"nav-link\" href=\"https://www.froala.com\">FAQ</a>\n              <a class=\"nav-link\" href=\"https://www.froala.com\">Support</a>\n            </nav>\n          </div>\n    \n          <div class=\"col-12 col-md-4 col-lg-3 text-md-left mt-5 mt-md-0\">\n            <h3><strong>About Us</strong></h3>\n            <p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.</p>\n          </div>\n    \n          <div class=\"col-12 col-lg-2 ml-auto text-lg-left mt-4 mt-lg-0\">\n            <h3><strong>Follow Us</strong></h3>\n            <p class=\"lead\">\n              <a href=\"https://www.froala.com\" class=\"mx-2\"><i class=\"fab fa-twitter\" aria-hidden=\"true\"></i></a>\n              <a href=\"https://www.froala.com\" class=\"mx-2\"><i class=\"fab fa-facebook\" aria-hidden=\"true\"></i></a>\n              <a href=\"https://www.froala.com\" class=\"mx-2\"><i class=\"fab fa-instagram\" aria-hidden=\"true\"></i></a>\n              <a href=\"https://www.froala.com\" class=\"mx-2\"><i class=\"fab fa-pinterest\" aria-hidden=\"true\"></i></a>\n              <a href=\"https://www.froala.com\" class=\"mx-2\"><i class=\"fab fa-google\" aria-hidden=\"true\"></i></a>\n            </p>\n          </div>\n        </div>\n    \n        <div class=\"row mt-3\">\n          <div class=\"col text-center\">\n            © 2018 Froala. All Rights Reserved\n          </div>\n        </div>\n      </div>\n    </footer>"
    },
    {
        "html": true,
        "name": "Footer_101",
        "data": "<footer class=\"fdb-block footer-large bg-dark\">\n      <div class=\"container\">\n        <div class=\"row align-items-top text-center text-md-left\">\n          <div class=\"col-12 col-sm-6 col-md-4\">\n            <h3><strong>Country A</strong></h3>\n            <p>Street Address 52<br>Contact Name</p>\n            <p>+44 827 312 5002</p>\n            <p><a href=\"https://www.froala.com\">countrya@amazing.com</a></p>\n          </div>\n    \n          <div class=\"col-12 col-sm-6 col-md-4 mt-4 mt-sm-0\">\n            <h3><strong>Country B</strong></h3>\n            <p>Street Address 100<br>Contact Name</p>\n            <p>+13 827 312 5002</p>\n            <p><a href=\"https://www.froala.com\">countryb@amazing.com</a></p>\n          </div>\n    \n          <div class=\"col-12 col-md-4 mt-5 mt-md-0 text-md-left\">\n            <h3><strong>About Us</strong></h3>\n            <p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.</p>\n          </div>\n        </div>\n    \n        <div class=\"row mt-5\">\n          <div class=\"col text-center\">\n            © 2018 Froala. All Rights Reserved\n          </div>\n        </div>\n      </div>\n    </footer>"
    },
    {
        "html": true,
        "name": "Footer_111",
        "data": "<footer class=\"fdb-block footer-small\">\n      <div class=\"container\">\n        <div class=\"row align-items-center text-center\">\n          <div class=\"col-12 col-lg-4 text-lg-left\">\n            © 2018 Froala\n          </div>\n    \n          <div class=\"col-12 col-lg-4 mt-4 mt-lg-0\">\n            <img alt=\"image\" src=\"https://heroic-empanada-f5b342.netlify.app/logo.png\" height=\"40\">\n          </div>\n    \n          <div class=\"col-12 col-lg-4 text-lg-right mt-4 mt-lg-0\">\n            <ul class=\"nav justify-content-lg-end justify-content-center\">\n              <li class=\"nav-item\">\n                <a class=\"nav-link\" href=\"https://www.froala.com\">Privacy</a>\n              </li>\n              <li class=\"nav-item\">\n                <a class=\"nav-link\" href=\"https://www.froala.com\">Terms</a>\n              </li>\n              <li class=\"nav-item\">\n                <a class=\"nav-link\" href=\"https://www.froala.com\">About</a>\n              </li>\n            </ul>\n          </div>\n        </div>\n      </div>\n    </footer>"
    },
    {
        "html": true,
        "name": "Footer_121",
        "data": "<footer class=\"fdb-block footer-large\">\n      <div class=\"container\">\n        <div class=\"row text-center\">\n          <div class=\"col\">\n            <h3>Company Name</h3>\n            <p>70 Bowman St.<br>South Windsor, CT 06074</p>\n            <p>USA</p>\n            <p>+13 827 312 5002</p>\n          </div>\n        </div>\n    \n        <div class=\"row mt-4\">\n          <div class=\"col text-center\">\n            <p class=\"lead\">\n              <a href=\"https://www.froala.com\" class=\"mx-2\"><i class=\"fab fa-twitter\" aria-hidden=\"true\"></i></a>\n              <a href=\"https://www.froala.com\" class=\"mx-2\"><i class=\"fab fa-facebook\" aria-hidden=\"true\"></i></a>\n              <a href=\"https://www.froala.com\" class=\"mx-2\"><i class=\"fab fa-instagram\" aria-hidden=\"true\"></i></a>\n              <a href=\"https://www.froala.com\" class=\"mx-2\"><i class=\"fab fa-pinterest\" aria-hidden=\"true\"></i></a>\n              <a href=\"https://www.froala.com\" class=\"mx-2\"><i class=\"fab fa-google\" aria-hidden=\"true\"></i></a>\n            </p>\n          </div>\n        </div>\n      </div>\n    </footer>"
    }
]