export default [
    {
        "html": true,
        "name": "FormBlock_11",
        "data": "<section class=\"fdb-block\">\n      <div class=\"container\">\n        <div class=\"row justify-content-center\">\n          <div class=\"col-12 col-md-8 col-lg-6 text-center\">\n            <h1>Subscribe</h1>\n            <div class=\"input-group mt-4 mb-4\">\n              <input type=\"text\" class=\"form-control\" placeholder=\"Enter your email address\">\n              <div class=\"input-group-append\">\n                <button class=\"btn btn-primary\" type=\"button\">Submit</button>\n              </div>\n            </div>\n    \n            <p class=\"h4\">Find us on <a href=\"https://www.Blocks.com\">Facebook</a> and <a href=\"https://www.Blocks.com\">Twitter</a>.</p>\n          </div>\n        </div>\n      </div>\n    </section>"
    },
    {
        "html": true,
        "name": "FormBlock_21",
        "data": "<section class=\"fdb-block\" style=\"background-image: url(https://heroic-empanada-f5b342.netlify.app/hero/blue.svg);\">\n      <div class=\"container\">\n        <div class=\"fdb-box\">\n          <div class=\"row justify-content-center align-items-center\">\n            <div class=\"col-12 col-lg-6\">\n              <h2>Join us!</h2>\n              <p class=\"lead\">Far far away, behind the word mountains, far from the countries Vokalia and Consonantia. </p>\n            </div>\n            <div class=\"col-12 col-lg-5 text-center\">\n              <div class=\"input-group mt-4\">\n                <input type=\"text\" class=\"form-control\" placeholder=\"Enter your email address\">\n                <div class=\"input-group-append\">\n                  <button class=\"btn btn-primary\" type=\"button\">Submit</button>\n                </div>\n              </div>\n            </div>\n          </div>\n        </div>\n      </div>\n    </section>"
    },
    {
        "html": true,
        "name": "FormBlock_31",
        "data": "<section class=\"fdb-block\">\n      <div class=\"container\">\n        <div class=\"row justify-content-center\">\n          <div class=\"col-12 col-lg-10 col-xl-8 text-center\">\n            <div class=\"row\">\n              <div class=\"col\">\n                <h1>Register</h1>\n                <p class=\"lead\">When she reached the first hills, she had a last view back on the skyline of her hometown.</p>\n              </div>\n            </div>\n            <div class=\"row align-items-center\">\n              <div class=\"col-12 col-md-5 mt-4\">\n                <input type=\"text\" class=\"form-control\" placeholder=\"Email\">\n              </div>\n              <div class=\"col-12 col-md-5 mt-4\">\n                <input type=\"password\" class=\"form-control\" placeholder=\"Password\">\n              </div>\n              <div class=\"col-12 col-md-2 mt-4\">\n                <button class=\"btn btn-secondary\" type=\"button\">Submit</button>\n              </div>\n            </div>\n          </div>\n        </div>\n      </div>\n    </section>"
    },
    {
        "html": true,
        "name": "FormBlock_41",
        "data": "<section class=\"fdb-block py-0\">\n      <div class=\"container py-5 my-5\" style=\"background-image: url(https://heroic-empanada-f5b342.netlify.app/shapes/6.svg);\">\n        <div class=\"row\">\n          <div class=\"col-12 col-md-8 col-lg-7 col-xl-5 text-left\">\n            <div class=\"row\">\n              <div class=\"col\">\n                <h1>Sign Up</h1>\n                <p class=\"lead\">Far far away, behind the word mountains, far from the countries Vokalia and Consonantia. </p>\n              </div>\n            </div>\n            <div class=\"row\">\n              <div class=\"col mt-4\">\n                <input type=\"text\" class=\"form-control\" placeholder=\"Email\">\n              </div>\n            </div>\n            <div class=\"row mt-4\">\n              <div class=\"col\">\n                <input type=\"password\" class=\"form-control\" placeholder=\"Password\">\n              </div>\n            </div>\n            <div class=\"row mt-4\">\n              <div class=\"col\">\n                <button class=\"btn btn-primary\" type=\"button\">Submit</button>\n              </div>\n            </div>\n          </div>\n        </div>\n      </div>\n    </section>"
    },
    {
        "html": true,
        "name": "FormBlock_51",
        "data": "<section class=\"fdb-block py-0\">\n      <div class=\"container py-5 my-5\" style=\"background-image: url(https://heroic-empanada-f5b342.netlify.app/shapes/4.svg);\">\n        <div class=\" row justify-content-end\">\n          <div class=\"col-12 col-md-8 col-lg-6 col-xl-5 text-left\">\n            <div class=\"fdb-box\">\n              <div class=\"row\">\n                <div class=\"col\">\n                  <h1>Log In</h1>\n                  <p class=\"lead\">Right at the coast of the Semantics, a large language ocean. A small river named Duden.</p>\n                </div>\n              </div>\n              <div class=\"row\">\n                <div class=\"col mt-4\">\n                  <input type=\"text\" class=\"form-control\" placeholder=\"Email\">\n                </div>\n              </div>\n              <div class=\"row mt-4\">\n                <div class=\"col\">\n                  <input type=\"password\" class=\"form-control\" placeholder=\"Password\">\n                </div>\n              </div>\n              <div class=\"row mt-4\">\n                <div class=\"col\">\n                  <button class=\"btn btn-secondary\" type=\"button\">Submit</button>\n                </div>\n              </div>\n            </div>\n          </div>\n        </div>\n      </div>\n    </section>"
    },
    {
        "html": true,
        "name": "FormBlock_61",
        "data": "<section class=\"fdb-block\">\n      <div class=\"container\">\n        <div class=\"row justify-content-center\">\n          <div class=\"col-12 col-md-8 col-lg-8 col-xl-6\">\n            <div class=\"row\">\n              <div class=\"col text-center\">\n                <h1>Register</h1>\n                <p class=\"lead\">Far far away, behind the word mountains, far from the countries Vokalia and Consonantia. </p>\n              </div>\n            </div>\n            <div class=\"row align-items-center\">\n              <div class=\"col mt-4\">\n                <input type=\"text\" class=\"form-control\" placeholder=\"Company Name\">\n              </div>\n            </div>\n            <div class=\"row align-items-center mt-4\">\n              <div class=\"col\">\n                <input type=\"email\" class=\"form-control\" placeholder=\"Email\">\n              </div>\n            </div>\n            <div class=\"row align-items-center mt-4\">\n              <div class=\"col\">\n                <input type=\"password\" class=\"form-control\" placeholder=\"Password\">\n              </div>\n              <div class=\"col\">\n                <input type=\"password\" class=\"form-control\" placeholder=\"Confirm Password\">\n              </div>\n            </div>\n            <div class=\"row justify-content-start mt-4\">\n              <div class=\"col\">\n                <div class=\"form-check\">\n                  <label class=\"form-check-label\">\n                      <input type=\"checkbox\" class=\"form-check-input\">\n                      I Read and Accept <a href=\"https://www.Blocks.com\">Terms and Conditions</a>\n                    </label>\n                </div>\n    \n                <button class=\"btn btn-primary mt-4\">Submit</button>\n              </div>\n            </div>\n          </div>\n        </div>\n      </div>\n    </section>"
    },
    {
        "html": true,
        "name": "FormBlock_71",
        "data": "<section class=\"fdb-block\" style=\"background-image: url(https://heroic-empanada-f5b342.netlify.app/hero/red.svg);\">\n      <div class=\"container\">\n        <div class=\"row justify-content-center\">\n          <div class=\"col-12 col-md-8 col-lg-7 col-xl-5 text-center\">\n            <div class=\"fdb-box\">\n              <div class=\"row\">\n                <div class=\"col\">\n                  <h1>Log In</h1>\n                </div>\n              </div>\n              <div class=\"row mt-4\">\n                <div class=\"col\">\n                  <input type=\"text\" class=\"form-control\" placeholder=\"Email\">\n                </div>\n              </div>\n              <div class=\"row mt-4\">\n                <div class=\"col\">\n                  <input type=\"password\" class=\"form-control mb-1\" placeholder=\"Password\">\n                  <p class=\"text-right\"><a href=\"https://www.Blocks.com\">Recover Password</a></p>\n                </div>\n              </div>\n              <div class=\"row mt-4\">\n                <div class=\"col\">\n                  <button class=\"btn btn-outline-secondary\" type=\"button\">Submit</button>\n                </div>\n              </div>\n            </div>\n          </div>\n        </div>\n      </div>\n    </section>"
    },
    {
        "html": true,
        "name": "FormBlock_81",
        "data": "<section class=\"fdb-block\">\n      <div class=\"container\">\n        <div class=\"row justify-content-center\">\n          <div class=\"col-12 col-md-8 col-lg-7 col-md-5 text-center\">\n            <div class=\"fdb-box fdb-touch\">\n              <div class=\"row\">\n                <div class=\"col\">\n                  <h1>Register</h1>\n                </div>\n              </div>\n              <div class=\"row\">\n                <div class=\"col mt-4\">\n                  <input type=\"text\" class=\"form-control\" placeholder=\"Name\">\n                </div>\n              </div>\n              <div class=\"row mt-4\">\n                <div class=\"col\">\n                  <input type=\"text\" class=\"form-control\" placeholder=\"Email\">\n                </div>\n              </div>\n              <div class=\"row mt-4\">\n                <div class=\"col\">\n                  <input type=\"password\" class=\"form-control mb-1\" placeholder=\"Password\">\n                  <p class=\"text-right\"><a href=\"https://www.Blocks.com\">Already have an account?</a></p>\n                </div>\n              </div>\n              <div class=\"row mt-4\">\n                <div class=\"col\">\n                  <button class=\"btn btn-primary\" type=\"button\">Submit</button>\n                </div>\n              </div>\n            </div>\n          </div>\n        </div>\n      </div>\n    </section>"
    },
    {
        "html": true,
        "name": "FormBlock_91",
        "data": "<section class=\"fdb-block bg-gray\">\n      <div class=\"container\">\n        <div class=\"row justify-content-center\">\n          <div class=\"col-12  col-md-10 col-lg-8 col-xl-6 text-center\">\n            <img alt=\"image\" height=\"40\" src=\"https://heroic-empanada-f5b342.netlify.app/icons/layers.svg\">\n            <h1>Never miss an update</h1>\n            <p class=\"lead\">Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. </p>\n            <div class=\"input-group mt-4 mb-4\">\n              <input type=\"text\" class=\"form-control\" placeholder=\"Enter your email address\">\n              <div class=\"input-group-append\">\n                <button class=\"btn btn-primary\" type=\"button\">Submit</button>\n              </div>\n            </div>\n            <p class=\"h5\"><em>*Your email address is safe with us. We never share your email address.</em></p>\n          </div>\n        </div>\n      </div>\n    </section>"
    },
    {
        "html": true,
        "name": "FormBlock_101",
        "data": "<section class=\"fdb-block\">\n      <div class=\"container\">\n        <div class=\"row justify-content-center\">\n          <div class=\"col-12 col-md-10 col-lg-8 col-xl-6 text-center\">\n            <h1>Company Name</h1>\n            <p class=\"lead\">When she reached the first hills of the Italic Mountains, she had a last view back on the skyline of her hometown.</p>\n            <div class=\"input-group mt-5 mb-5\">\n              <input type=\"text\" class=\"form-control\" placeholder=\"Enter your email address\">\n              <div class=\"input-group-append\">\n                <button class=\"btn btn-primary\" type=\"button\">Submit</button>\n              </div>\n            </div>\n            <p class=\"h2\">\n              <a href=\"https://www.Blocks.com\" class=\"mx-2\"><i class=\"fab fa-facebook\"></i></a>\n              <a href=\"https://www.Blocks.com\" class=\"mx-2\"><i class=\"fab fa-twitter\"></i></a>\n              <a href=\"https://www.Blocks.com\" class=\"mx-2\"><i class=\"fab fa-instagram\"></i></a>\n              <a href=\"https://www.Blocks.com\" class=\"mx-2\"><i class=\"fab fa-google\"></i></a>\n              <a href=\"https://www.Blocks.com\" class=\"mx-2\"><i class=\"fab fa-pinterest\"></i></a>\n            </p>\n          </div>\n        </div>\n      </div>\n    </section>"
    },
    {
        "html": true,
        "name": "FormBlock_111",
        "data": "<section class=\"fdb-block\">\n      <div class=\"container\">\n        <div class=\"row\">\n          <div class=\"col-12 col-md-6 m-md-auto ml-lg-0 col-lg-5\">\n            <img alt=\"image\" class=\"img-fluid\" src=\"https://heroic-empanada-f5b342.netlify.app/draws/group-chat.svg\">\n          </div>\n          <div class=\"col-12 col-md-10 col-lg-6 mt-4 mt-lg-0 ml-auto mr-auto ml-lg-auto text-left\">\n            <div class=\"row\">\n              <div class=\"col\">\n                <h1>Subscribe</h1>\n                <p class=\"lead\">Far far away, behind the word mountains, far from the countries Vokalia and Consonantia. </p>\n              </div>\n            </div>\n            <div class=\"row mt-4\">\n              <div class=\"col\">\n                <div class=\"input-group\">\n                  <input type=\"text\" class=\"form-control\" placeholder=\"Enter your email address\">\n                  <div class=\"input-group-append\">\n                    <button class=\"btn btn-primary\" type=\"button\">Submit</button>\n                  </div>\n                </div>\n              </div>\n            </div>\n    \n            <div class=\"row\">\n              <div class=\"col\">\n                <p class=\"h4\">* Leave your email address to be notified first.</p>\n              </div>\n            </div>\n          </div>\n        </div>\n      </div>\n    </section>"
    },
    {
        "html": true,
        "name": "FormBlock_121",
        "data": "<section class=\"fdb-block\" style=\"background-image: url(https://heroic-empanada-f5b342.netlify.app/shapes/1.svg);\">\n      <div class=\"container\">\n        <div class=\"row justify-content-end\">\n          <div class=\"col-12 col-md-9 col-lg-8\">\n            <div class=\"fdb-box fdb-touch\">\n              <div class=\"row justify-content-center\">\n                <div class=\"col-12 col-lg-10\">\n                  <h1>Subscribe</h1>\n                  <p class=\"lead\">When she reached the first hills of the Italic Mountains, she had a last view back on the skyline of her hometown Bookmarksgrove.</p>\n                </div>\n              </div>\n              <div class=\"row justify-content-center mt-4\">\n                <div class=\"col-12 col-lg-10\">\n                  <div class=\"input-group\">\n                    <input type=\"text\" class=\"form-control\" placeholder=\"Enter your email address\">\n                    <div class=\"input-group-append\">\n                      <button class=\"btn btn-primary\" type=\"button\">Submit</button>\n                    </div>\n                  </div>\n                </div>\n              </div>\n            </div>\n          </div>\n        </div>\n      </div>\n    </section>"
    }
]