export default [
  {
      "html": true,
      "name": "CallToAction_21",
      "data": "\n        <nav class=\"navbar navbar-expand-md bg-white\">\n          <button class=\"navbar-toggler\" type=\"button\" data-toggle=\"collapse\" data-target=\"#navbarNav0\" aria-controls=\"navbarNav0\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">\n            <span class=\"navbar-toggler-icon\"></span>\n          </button>\n    \n          <div class=\"collapse navbar-collapse\" id=\"navbarNav0\">\n            <ul class=\"navbar-nav mr-auto ml-auto\">\n              <li class=\"nav-item active\">\n                <a class=\"nav-link\" href=\"https://www.froala.com\">Home <span class=\"sr-only\">(current)</span></a>\n              </li>\n              <li class=\"nav-item\">\n                <a class=\"nav-link\" href=\"https://www.froala.com\">Features</a>\n              </li>\n              <li class=\"nav-item\">\n                <a class=\"nav-link\" href=\"https://www.froala.com\">Pricing</a>\n              </li>\n              <li class=\"nav-item\">\n                <a class=\"nav-link\" href=\"https://www.froala.com\">Team</a>\n              </li>\n            </ul>\n          </div>\n        </nav>\n      "
  },
  {
      "html": true,
      "name": "CallToAction_31",
      "data": "\n        <nav class=\"navbar navbar-expand-md bg-white\">\n          <a class=\"navbar-brand\" href=\"https://www.froala.com\">\n            <img src=\"https://heroic-empanada-f5b342.netlify.app/logo.png\" height=\"30\" alt=\"image\">\n          </a>\n    \n          <button class=\"navbar-toggler\" type=\"button\" data-toggle=\"collapse\" data-target=\"#navbarNav1\" aria-controls=\"navbarNav1\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">\n            <span class=\"navbar-toggler-icon\"></span>\n          </button>\n    \n          <div class=\"collapse navbar-collapse\" id=\"navbarNav1\">\n            <ul class=\"navbar-nav mr-auto\">\n              <li class=\"nav-item active\">\n                <a class=\"nav-link\" href=\"https://www.froala.com\">Home <span class=\"sr-only\">(current)</span></a>\n              </li>\n              <li class=\"nav-item\">\n                <a class=\"nav-link\" href=\"https://www.froala.com\">Features</a>\n              </li>\n              <li class=\"nav-item\">\n                <a class=\"nav-link\" href=\"https://www.froala.com\">Pricing</a>\n              </li>\n              <li class=\"nav-item\">\n                <a class=\"nav-link\" href=\"https://www.froala.com\">Team</a>\n              </li>\n            </ul>\n    \n            <ul class=\"navbar-nav justify-content-end d-none d-lg-flex ml-md-auto\">\n              <li class=\"nav-item\">\n                <a class=\"nav-link\" href=\"https://www.froala.com\"><i class=\"fab fa-slack\"></i></a>\n              </li>\n              <li class=\"nav-item\">\n                <a class=\"nav-link\" href=\"https://www.froala.com\"><i class=\"fab fa-twitter\"></i></a>\n              </li>\n              <li class=\"nav-item\">\n                <a class=\"nav-link\" href=\"https://www.froala.com\"><i class=\"fab fa-github\"></i></a>\n              </li>\n            </ul>\n    \n            <a class=\"btn btn-outline-primary ml-md-3\" href=\"https://www.froala.com\">Button</a>\n          </div>\n        </nav>\n      "
  },
  {
      "html": true,
      "name": "CallToAction_41",
      "data": "\n        <nav class=\"navbar navbar-expand-md no-gutters bg-white\">\n          <button class=\"navbar-toggler\" type=\"button\" data-toggle=\"collapse\" data-target=\"#navbarNav2\" aria-controls=\"navbarNav2\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">\n            <span class=\"navbar-toggler-icon\"></span>\n          </button>\n    \n          <div class=\"col-4 col-md-2 text-right text-md-center order-lg-6\">\n            <a href=\"https://www.froala.com\">\n              <img src=\"https://heroic-empanada-f5b342.netlify.app/logo.png\" height=\"30\" alt=\"image\">\n            </a>\n          </div>\n    \n          <div class=\"collapse navbar-collapse col-12 col-md-5 order-lg-1\" id=\"navbarNav2\">\n            <ul class=\"navbar-nav col-5\">\n              <li class=\"nav-item active\">\n                <a class=\"nav-link\" href=\"https://www.froala.com\">Home <span class=\"sr-only\">(current)</span></a>\n              </li>\n              <li class=\"nav-item\">\n                <a class=\"nav-link\" href=\"https://www.froala.com\">Features</a>\n              </li>\n              <li class=\"nav-item\">\n                <a class=\"nav-link\" href=\"https://www.froala.com\">Pricing</a>\n              </li>\n              <li class=\"nav-item\">\n                <a class=\"nav-link\" href=\"https://www.froala.com\">Team</a>\n              </li>\n            </ul>\n          </div>\n    \n          <ul class=\"navbar-nav justify-content-end col-sm-5 order-lg-12 d-none d-md-flex\">\n            <li class=\"nav-item\">\n              <a class=\"nav-link\" href=\"https://www.froala.com\"><i class=\"fab fa-twitter\"></i></a>\n            </li>\n            <li class=\"nav-item\">\n              <a class=\"nav-link\" href=\"https://www.froala.com\"><i class=\"fab fa-github\"></i></a>\n            </li>\n            <li class=\"nav-item\">\n              <a class=\"nav-link\" href=\"https://www.froala.com\"><i class=\"fab fa-slack\"></i></a>\n            </li>\n          </ul>\n        </nav>\n      "
  },
  {
      "html": true,
      "name": "CallToAction_51",
      "data": "\n        <nav class=\"navbar navbar-expand-md bg-white\">\n          <a class=\"navbar-brand\" href=\"https://www.froala.com\">\n            <img src=\"https://heroic-empanada-f5b342.netlify.app/logo.png\" height=\"30\" alt=\"image\">\n          </a>\n    \n          <button class=\"navbar-toggler\" type=\"button\" data-toggle=\"collapse\" data-target=\"#navbarNav3\" aria-controls=\"navbarNav3\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">\n            <span class=\"navbar-toggler-icon\"></span>\n          </button>\n    \n          <div class=\"collapse navbar-collapse\" id=\"navbarNav3\">\n            <ul class=\"navbar-nav ml-auto\">\n              <li class=\"nav-item active\">\n                <a class=\"nav-link\" href=\"https://www.froala.com\">Home <span class=\"sr-only\">(current)</span></a>\n              </li>\n              <li class=\"nav-item\">\n                <a class=\"nav-link\" href=\"https://www.froala.com\">Features</a>\n              </li>\n              <li class=\"nav-item\">\n                <a class=\"nav-link\" href=\"https://www.froala.com\">Pricing</a>\n              </li>\n              <li class=\"nav-item\">\n                <a class=\"nav-link\" href=\"https://www.froala.com\">Team</a>\n              </li>\n              <li class=\"nav-item\">\n                <a class=\"nav-link\" href=\"https://www.froala.com\">About</a>\n              </li>\n            </ul>\n    \n            <a class=\"btn btn-outline-primary ml-md-3\" href=\"https://www.froala.com\">Button</a>\n          </div>\n        </nav>\n      "
  },
  {
      "html": true,
      "name": "CallToAction_61",
      "data": "\n        <nav class=\"navbar navbar-expand-md no-gutters bg-white\">\n          <div class=\"col-2 text-left\">\n            <a href=\"https://www.froala.com\">\n              <img src=\"https://heroic-empanada-f5b342.netlify.app/logo.png\" height=\"30\" alt=\"image\">\n            </a>\n          </div>\n    \n          <button class=\"navbar-toggler\" type=\"button\" data-toggle=\"collapse\" data-target=\"#navbarNav4\" aria-controls=\"navbarNav4\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">\n            <span class=\"navbar-toggler-icon\"></span>\n          </button>\n    \n          <div class=\"collapse navbar-collapse justify-content-center col-md-8\" id=\"navbarNav4\">\n            <ul class=\"navbar-nav justify-content-center\">\n              <li class=\"nav-item active\">\n                <a class=\"nav-link\" href=\"https://www.froala.com\">Home <span class=\"sr-only\">(current)</span></a>\n              </li>\n              <li class=\"nav-item\">\n                <a class=\"nav-link\" href=\"https://www.froala.com\">Features</a>\n              </li>\n              <li class=\"nav-item\">\n                <a class=\"nav-link\" href=\"https://www.froala.com\">Pricing</a>\n              </li>\n              <li class=\"nav-item\">\n                <a class=\"nav-link\" href=\"https://www.froala.com\">Team</a>\n              </li>\n            </ul>\n          </div>\n    \n          <ul class=\"navbar-nav col-2 justify-content-end d-none d-md-flex\">\n            <li class=\"nav-item\">\n              <a class=\"nav-link\" href=\"https://www.froala.com\"><i class=\"fab fa-facebook\"></i></a>\n            </li>\n            <li class=\"nav-item\">\n              <a class=\"nav-link\" href=\"https://www.froala.com\"><i class=\"fab fa-twitter\"></i></a>\n            </li>\n            <li class=\"nav-item\">\n              <a class=\"nav-link\" href=\"https://www.froala.com\"><i class=\"fab fa-github\"></i></a>\n            </li>\n            <li class=\"nav-item\">\n              <a class=\"nav-link\" href=\"https://www.froala.com\"><i class=\"fab fa-google\"></i></a>\n            </li>\n          </ul>\n        </nav>\n      "
  },
  {
      "html": true,
      "name": "CallToAction_71",
      "data": "\n        <nav class=\"navbar navbar-expand-lg bg-white\">\n          <a class=\"navbar-brand\" href=\"https://www.froala.com\">\n            <img src=\"https://heroic-empanada-f5b342.netlify.app/logo.png\" height=\"30\" alt=\"image\">\n          </a>\n    \n          <button class=\"navbar-toggler\" type=\"button\" data-toggle=\"collapse\" data-target=\"#navbarNav5\" aria-controls=\"navbarNav5\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">\n            <span class=\"navbar-toggler-icon\"></span>\n          </button>\n    \n          <div class=\"collapse navbar-collapse\" id=\"navbarNav5\">\n            <ul class=\"navbar-nav mr-auto\">\n              <li class=\"nav-item active\">\n                <a class=\"nav-link\" href=\"https://www.froala.com\">Home <span class=\"sr-only\">(current)</span></a>\n              </li>\n              <li class=\"nav-item\">\n                <a class=\"nav-link\" href=\"https://www.froala.com\">Features</a>\n              </li>\n              <li class=\"nav-item\">\n                <a class=\"nav-link\" href=\"https://www.froala.com\">Pricing</a>\n              </li>\n              <li class=\"nav-item\">\n                <a class=\"nav-link\" href=\"https://www.froala.com\">Team</a>\n              </li>\n            </ul>\n    \n            <ul class=\"navbar-nav justify-content-end ml-auto\">\n              <li class=\"nav-item\">\n                <a class=\"nav-link\" href=\"https://www.froala.com\">Docs</a>\n              </li>\n              <li class=\"nav-item\">\n                <a class=\"nav-link\" href=\"https://www.froala.com\">Contact</a>\n              </li>\n              <li class=\"nav-item\">\n                <a class=\"nav-link\" href=\"https://www.froala.com\">Log In</a>\n              </li>\n            </ul>\n    \n            <a class=\"btn btn-primary ml-md-3\" href=\"https://www.froala.com\">Button</a>\n          </div>\n        </nav>\n      "
  },
  {
      "html": true,
      "name": "CallToAction_81",
      "data": "\n        <nav class=\"navbar navbar-expand-md no-gutters bg-white\">\n          <div class=\"col-2 text-left\">\n            <a href=\"https://www.froala.com\">\n              <img src=\"https://heroic-empanada-f5b342.netlify.app/logo.png\" height=\"30\" alt=\"image\">\n            </a>\n          </div>\n    \n          <button class=\"navbar-toggler\" type=\"button\" data-toggle=\"collapse\" data-target=\".navbar-collapse-1\" aria-controls=\"navbarNav6\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">\n            <span class=\"navbar-toggler-icon\"></span>\n          </button>\n    \n          <div class=\"collapse navbar-collapse justify-content-center col-md-8 navbar-collapse-1\">\n            <ul class=\"navbar-nav justify-content-center\">\n              <li class=\"nav-item active\">\n                <a class=\"nav-link\" href=\"https://www.froala.com\">Home <span class=\"sr-only\">(current)</span></a>\n              </li>\n              <li class=\"nav-item\">\n                <a class=\"nav-link\" href=\"https://www.froala.com\">Features</a>\n              </li>\n              <li class=\"nav-item\">\n                <a class=\"nav-link\" href=\"https://www.froala.com\">Pricing</a>\n              </li>\n              <li class=\"nav-item\">\n                <a class=\"nav-link\" href=\"https://www.froala.com\">Team</a>\n              </li>\n              <li class=\"nav-item\">\n                <a class=\"nav-link\" href=\"https://www.froala.com\">Contact</a>\n              </li>\n            </ul>\n          </div>\n    \n          <div class=\"collapse navbar-collapse justify-content-end col-md-2 navbar-collapse-1\">\n            <ul class=\"navbar-nav\">\n              <li class=\"nav-item\">\n                <a class=\"nav-link\" href=\"https://www.froala.com\">Log In <i class=\"fas fa-sign-in-alt\"></i></a>\n              </li>\n            </ul>\n          </div>\n        </nav>\n      "
  },
  {
      "html": true,
      "name": "CallToAction_91",
      "data": "\n        <nav class=\"navbar navbar-expand-md no-gutters bg-white\">\n          <div class=\"col-3 text-left\">\n            <a href=\"https://www.froala.com\">\n              <img src=\"https://heroic-empanada-f5b342.netlify.app/logo.png\" height=\"30\" alt=\"image\">\n            </a>\n          </div>\n    \n          <button class=\"navbar-toggler\" type=\"button\" data-toggle=\"collapse\" data-target=\".navbar-collapse-2\" aria-controls=\"navbarNav7\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">\n            <span class=\"navbar-toggler-icon\"></span>\n          </button>\n    \n          <div class=\"collapse navbar-collapse navbar-collapse-2 justify-content-center col-md-6\" id=\"navbarNav7\">\n            <ul class=\"navbar-nav justify-content-center\">\n              <li class=\"nav-item active\">\n                <a class=\"nav-link\" href=\"https://www.froala.com\">Home <span class=\"sr-only\">(current)</span></a>\n              </li>\n              <li class=\"nav-item\">\n                <a class=\"nav-link\" href=\"https://www.froala.com\">Features</a>\n              </li>\n              <li class=\"nav-item\">\n                <a class=\"nav-link\" href=\"https://www.froala.com\">Pricing</a>\n              </li>\n              <li class=\"nav-item\">\n                <a class=\"nav-link\" href=\"https://www.froala.com\">Team</a>\n              </li>\n              <li class=\"nav-item\">\n                <a class=\"nav-link\" href=\"https://www.froala.com\">Contact</a>\n              </li>\n            </ul>\n          </div>\n    \n          <div class=\"collapse navbar-collapse navbar-collapse-2\">\n            <ul class=\"navbar-nav ml-auto justify-content-end\">\n              <li class=\"nav-item\">\n                <a class=\"nav-link\" href=\"https://www.froala.com\">Log In</a>\n              </li>\n            </ul>\n    \n            <a class=\"btn btn-primary ml-md-3\" href=\"https://www.froala.com\">Register</a>\n          </div>\n        </nav>\n      "
  },
  {
      "html": true,
      "name": "CallToAction_101",
      "data": "\n        <nav class=\"navbar bg-white\">\n          <a href=\"https://www.froala.com\">\n            <img src=\"https://heroic-empanada-f5b342.netlify.app/logo.png\" height=\"30\" alt=\"image\">\n          </a>\n        </nav>\n      "
  },
  {
      "html": true,
      "name": "CallToAction_111",
      "data": "\n        <nav class=\"navbar bg-white\">\n          <a class=\"ml-auto mr-auto\" href=\"https://www.froala.com\">\n            <img src=\"https://heroic-empanada-f5b342.netlify.app/logo.png\" height=\"30\" alt=\"image\">\n          </a>\n        </nav>\n      "
  },
  {
      "html": true,
      "name": "CallToAction_121",
      "data": "\n        <nav class=\"navbar navbar-expand-md bg-white\">\n          <button class=\"navbar-toggler\" type=\"button\" data-toggle=\"collapse\" data-target=\"#navbarNav8\" aria-controls=\"navbarNav8\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">\n            <span class=\"navbar-toggler-icon\"></span>\n          </button>\n    \n          <div class=\"collapse navbar-collapse\" id=\"navbarNav8\">\n            <ul class=\"navbar-nav mr-auto ml-auto\">\n              <li class=\"nav-item active\">\n                <a class=\"nav-link\" href=\"https://www.froala.com\">Home <span class=\"sr-only\">(current)</span></a>\n              </li>\n              <li class=\"nav-item\">\n                <a class=\"nav-link\" href=\"https://www.froala.com\">Features</a>\n              </li>\n              <li class=\"nav-item\">\n                <a class=\"nav-link\" href=\"https://www.froala.com\">Pricing</a>\n              </li>\n              <li class=\"nav-item\">\n                <a class=\"nav-link\" href=\"https://www.froala.com\">Team</a>\n              </li>\n            </ul>\n          </div>\n        </nav>\n      "
  },
  {
      "html": true,
      "name": "CallToAction_131",
      "data": "\n        <nav class=\"navbar navbar-expand-md bg-white\">\n          <a class=\"navbar-brand\" href=\"https://www.froala.com\">\n            <img src=\"https://heroic-empanada-f5b342.netlify.app/logo.png\" height=\"30\" alt=\"image\">\n          </a>\n    \n          <button class=\"navbar-toggler\" type=\"button\" data-toggle=\"collapse\" data-target=\"#navbarNav9\" aria-controls=\"navbarNav9\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">\n            <span class=\"navbar-toggler-icon\"></span>\n          </button>\n    \n          <div class=\"collapse navbar-collapse\" id=\"navbarNav9\">\n            <ul class=\"navbar-nav mr-auto\">\n              <li class=\"nav-item active\">\n                <a class=\"nav-link\" href=\"https://www.froala.com\">Home <span class=\"sr-only\">(current)</span></a>\n              </li>\n              <li class=\"nav-item\">\n                <a class=\"nav-link\" href=\"https://www.froala.com\">Features</a>\n              </li>\n              <li class=\"nav-item\">\n                <a class=\"nav-link\" href=\"https://www.froala.com\">Pricing</a>\n              </li>\n              <li class=\"nav-item\">\n                <a class=\"nav-link\" href=\"https://www.froala.com\">Team</a>\n              </li>\n            </ul>\n    \n            <ul class=\"navbar-nav justify-content-end d-none d-lg-flex ml-md-auto\">\n              <li class=\"nav-item active\">\n                <a class=\"nav-link\" href=\"https://www.froala.com\"><i class=\"fab fa-slack\"></i></a>\n              </li>\n              <li class=\"nav-item\">\n                <a class=\"nav-link\" href=\"https://www.froala.com\"><i class=\"fab fa-twitter\"></i></a>\n              </li>\n              <li class=\"nav-item\">\n                <a class=\"nav-link\" href=\"https://www.froala.com\"><i class=\"fab fa-github\"></i></a>\n              </li>\n            </ul>\n    \n            <a class=\"btn btn-outline-light ml-md-3\" href=\"https://www.froala.com\">Button</a>\n          </div>\n        </nav>\n      "
  },
  {
      "html": true,
      "name": "CallToAction_141",
      "data": "\n        <nav class=\"navbar navbar-expand-md no-gutters bg-white\">\n          <button class=\"navbar-toggler\" type=\"button\" data-toggle=\"collapse\" data-target=\"#navbarNav10\" aria-controls=\"navbarNav10\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">\n            <span class=\"navbar-toggler-icon\"></span>\n          </button>\n    \n          <div class=\"col-4 col-sm-2 text-center order-lg-6\">\n            <a href=\"https://www.froala.com\">\n              <img src=\"https://heroic-empanada-f5b342.netlify.app/logo.png\" height=\"30\" alt=\"image\">\n            </a>\n          </div>\n    \n          <div class=\"collapse navbar-collapse col-12 col-md-5 order-lg-1\" id=\"navbarNav10\">\n            <ul class=\"navbar-nav col-5\">\n              <li class=\"nav-item active\">\n                <a class=\"nav-link\" href=\"https://www.froala.com\">Home <span class=\"sr-only\">(current)</span></a>\n              </li>\n              <li class=\"nav-item\">\n                <a class=\"nav-link\" href=\"https://www.froala.com\">Features</a>\n              </li>\n              <li class=\"nav-item\">\n                <a class=\"nav-link\" href=\"https://www.froala.com\">Pricing</a>\n              </li>\n              <li class=\"nav-item\">\n                <a class=\"nav-link\" href=\"https://www.froala.com\">Team</a>\n              </li>\n            </ul>\n          </div>\n    \n          <ul class=\"navbar-nav justify-content-end col-sm-5 order-lg-12 d-none d-md-flex\">\n            <li class=\"nav-item\">\n              <a class=\"nav-link\" href=\"https://www.froala.com\"><i class=\"fab fa-twitter\"></i></a>\n            </li>\n            <li class=\"nav-item\">\n              <a class=\"nav-link\" href=\"https://www.froala.com\"><i class=\"fab fa-github\"></i></a>\n            </li>\n            <li class=\"nav-item\">\n              <a class=\"nav-link\" href=\"https://www.froala.com\"><i class=\"fab fa-slack\"></i></a>\n            </li>\n          </ul>\n        </nav>\n      "
  },
  {
      "html": true,
      "name": "CallToAction_151",
      "data": "\n        <nav class=\"navbar navbar-expand-md bg-white\">\n          <a class=\"navbar-brand\" href=\"https://www.froala.com\">\n            <img src=\"https://heroic-empanada-f5b342.netlify.app/logo.png\" height=\"30\" alt=\"image\">\n          </a>\n    \n          <button class=\"navbar-toggler\" type=\"button\" data-toggle=\"collapse\" data-target=\"#navbarNav11\" aria-controls=\"navbarNav11\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">\n            <span class=\"navbar-toggler-icon\"></span>\n          </button>\n    \n          <div class=\"collapse navbar-collapse\" id=\"navbarNav11\">\n            <ul class=\"navbar-nav ml-auto\">\n              <li class=\"nav-item active\">\n                <a class=\"nav-link\" href=\"https://www.froala.com\">Home <span class=\"sr-only\">(current)</span></a>\n              </li>\n              <li class=\"nav-item\">\n                <a class=\"nav-link\" href=\"https://www.froala.com\">Features</a>\n              </li>\n              <li class=\"nav-item\">\n                <a class=\"nav-link\" href=\"https://www.froala.com\">Pricing</a>\n              </li>\n              <li class=\"nav-item\">\n                <a class=\"nav-link\" href=\"https://www.froala.com\">Team</a>\n              </li>\n              <li class=\"nav-item\">\n                <a class=\"nav-link\" href=\"https://www.froala.com\">About</a>\n              </li>\n            </ul>\n    \n            <a class=\"btn btn-outline-light ml-md-3\" href=\"https://www.froala.com\">Button</a>\n          </div>\n        </nav>\n      "
  },
  {
      "html": true,
      "name": "CallToAction_161",
      "data": "\n        <nav class=\"navbar navbar-expand-md no-gutters\">\n          <div class=\"col-2 text-left\">\n            <a href=\"https://www.froala.com\">\n              <img src=\"https://heroic-empanada-f5b342.netlify.app/logo.png\" height=\"30\" alt=\"image\">\n            </a>\n          </div>\n    \n          <button class=\"navbar-toggler\" type=\"button\" data-toggle=\"collapse\" data-target=\"#navbarNav12\" aria-controls=\"navbarNav12\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">\n            <span class=\"navbar-toggler-icon\"></span>\n          </button>\n    \n          <div class=\"collapse navbar-collapse justify-content-center col-md-8\" id=\"navbarNav12\">\n            <ul class=\"navbar-nav justify-content-center\">\n              <li class=\"nav-item active\">\n                <a class=\"nav-link\" href=\"https://www.froala.com\">Home <span class=\"sr-only\">(current)</span></a>\n              </li>\n              <li class=\"nav-item\">\n                <a class=\"nav-link\" href=\"https://www.froala.com\">Features</a>\n              </li>\n              <li class=\"nav-item\">\n                <a class=\"nav-link\" href=\"https://www.froala.com\">Pricing</a>\n              </li>\n              <li class=\"nav-item\">\n                <a class=\"nav-link\" href=\"https://www.froala.com\">Team</a>\n              </li>\n            </ul>\n          </div>\n    \n          <ul class=\"navbar-nav col-2 justify-content-end d-none d-md-flex\">\n            <li class=\"nav-item active\">\n              <a class=\"nav-link\" href=\"https://www.froala.com\"><i class=\"fab fa-facebook\"></i></a>\n            </li>\n            <li class=\"nav-item\">\n              <a class=\"nav-link\" href=\"https://www.froala.com\"><i class=\"fab fa-twitter\"></i></a>\n            </li>\n            <li class=\"nav-item\">\n              <a class=\"nav-link\" href=\"https://www.froala.com\"><i class=\"fab fa-github\"></i></a>\n            </li>\n            <li class=\"nav-item\">\n              <a class=\"nav-link\" href=\"https://www.froala.com\"><i class=\"fab fa-google\"></i></a>\n            </li>\n          </ul>\n        </nav>\n      "
  },
  {
      "html": true,
      "name": "CallToAction_171",
      "data": "\n        <nav class=\"navbar navbar-expand-lg\">\n          <a class=\"navbar-brand\" href=\"https://www.froala.com\">\n            <img src=\"https://heroic-empanada-f5b342.netlify.app/logo.png\" height=\"30\" alt=\"image\">\n          </a>\n    \n          <button class=\"navbar-toggler\" type=\"button\" data-toggle=\"collapse\" data-target=\"#navbarNav13\" aria-controls=\"navbarNav13\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">\n            <span class=\"navbar-toggler-icon\"></span>\n          </button>\n    \n          <div class=\"collapse navbar-collapse\" id=\"navbarNav13\">\n            <ul class=\"navbar-nav mr-auto\">\n              <li class=\"nav-item active\">\n                <a class=\"nav-link\" href=\"https://www.froala.com\">Home <span class=\"sr-only\">(current)</span></a>\n              </li>\n              <li class=\"nav-item\">\n                <a class=\"nav-link\" href=\"https://www.froala.com\">Features</a>\n              </li>\n              <li class=\"nav-item\">\n                <a class=\"nav-link\" href=\"https://www.froala.com\">Pricing</a>\n              </li>\n              <li class=\"nav-item\">\n                <a class=\"nav-link\" href=\"https://www.froala.com\">Team</a>\n              </li>\n            </ul>\n    \n            <ul class=\"navbar-nav justify-content-end ml-auto\">\n              <li class=\"nav-item\">\n                <a class=\"nav-link\" href=\"https://www.froala.com\">Docs</a>\n              </li>\n              <li class=\"nav-item\">\n                <a class=\"nav-link\" href=\"https://www.froala.com\">Contact</a>\n              </li>\n              <li class=\"nav-item\">\n                <a class=\"nav-link\" href=\"https://www.froala.com\">Log In</a>\n              </li>\n            </ul>\n    \n            <a class=\"btn btn-light ml-md-3\" href=\"https://www.froala.com\">Button</a>\n          </div>\n        </nav>\n      "
  },
  {
      "html": true,
      "name": "CallToAction_181",
      "data": "\n        <nav class=\"navbar navbar-expand-md no-gutters\">\n          <div class=\"col-2 text-left\">\n            <a href=\"https://www.froala.com\">\n              <img src=\"https://heroic-empanada-f5b342.netlify.app/logo.png\" height=\"30\" alt=\"image\">\n            </a>\n          </div>\n    \n          <button class=\"navbar-toggler\" type=\"button\" data-toggle=\"collapse\" data-target=\".navbar-collapse-3\" aria-controls=\"navbarNav14\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">\n            <span class=\"navbar-toggler-icon\"></span>\n          </button>\n    \n          <div class=\"collapse navbar-collapse justify-content-center col-md-8 navbar-collapse-3\" id=\"navbarNav14\">\n            <ul class=\"navbar-nav justify-content-center\">\n              <li class=\"nav-item active\">\n                <a class=\"nav-link\" href=\"https://www.froala.com\">Home <span class=\"sr-only\">(current)</span></a>\n              </li>\n              <li class=\"nav-item\">\n                <a class=\"nav-link\" href=\"https://www.froala.com\">Features</a>\n              </li>\n              <li class=\"nav-item\">\n                <a class=\"nav-link\" href=\"https://www.froala.com\">Pricing</a>\n              </li>\n              <li class=\"nav-item\">\n                <a class=\"nav-link\" href=\"https://www.froala.com\">Team</a>\n              </li>\n              <li class=\"nav-item\">\n                <a class=\"nav-link\" href=\"https://www.froala.com\">Contact</a>\n              </li>\n            </ul>\n          </div>\n    \n          <div class=\"collapse navbar-collapse justify-content-end col-md-2 navbar-collapse-3\">\n            <ul class=\"navbar-nav\">\n              <li class=\"nav-item\">\n                <a class=\"nav-link\" href=\"https://www.froala.com\">Log In <i class=\"fas fa-sign-in-alt\"></i></a>\n              </li>\n            </ul>\n          </div>\n        </nav>\n      "
  },
  {
      "html": true,
      "name": "CallToAction_191",
      "data": "\n        <nav class=\"navbar navbar-expand-md no-gutters\">\n          <div class=\"col-3 text-left\">\n            <a href=\"https://www.froala.com\">\n              <img src=\"https://heroic-empanada-f5b342.netlify.app/logo.png\" height=\"30\" alt=\"image\">\n            </a>\n          </div>\n    \n          <button class=\"navbar-toggler\" type=\"button\" data-toggle=\"collapse\" data-target=\".navbar-collapse-4\" aria-controls=\"navbarNav15\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">\n            <span class=\"navbar-toggler-icon\"></span>\n          </button>\n    \n          <div class=\"collapse navbar-collapse navbar-collapse-4 justify-content-center col-md-6\" id=\"navbarNav15\">\n            <ul class=\"navbar-nav justify-content-center\">\n              <li class=\"nav-item active\">\n                <a class=\"nav-link\" href=\"https://www.froala.com\">Home <span class=\"sr-only\">(current)</span></a>\n              </li>\n              <li class=\"nav-item\">\n                <a class=\"nav-link\" href=\"https://www.froala.com\">Features</a>\n              </li>\n              <li class=\"nav-item\">\n                <a class=\"nav-link\" href=\"https://www.froala.com\">Pricing</a>\n              </li>\n              <li class=\"nav-item\">\n                <a class=\"nav-link\" href=\"https://www.froala.com\">Team</a>\n              </li>\n              <li class=\"nav-item\">\n                <a class=\"nav-link\" href=\"https://www.froala.com\">Contact</a>\n              </li>\n            </ul>\n          </div>\n    \n          <div class=\"collapse navbar-collapse navbar-collapse-4\">\n            <ul class=\"navbar-nav ml-auto justify-content-end\">\n              <li class=\"nav-item\">\n                <a class=\"nav-link\" href=\"https://www.froala.com\">Log In</a>\n              </li>\n            </ul>\n    \n            <a class=\"btn btn-primary ml-md-3\" href=\"https://www.froala.com\">Register</a>\n          </div>\n        </nav>\n      "
  }
]